In [32]:
from sklearn.tree import DecisionTreeClassifier
import zipfile
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [3]:
with zipfile.ZipFile('/content/archive (8).zip','r') as zip_ref:
  zip_ref.extractall('/content')

In [6]:
df = pd.read_csv('/content/Titanic-Dataset.csv')
df.shape
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [43]:
X = df.drop("Survived", axis = 1)
y = df["Survived"]

In [44]:
X = X.drop(columns=["Name", "Ticket", "Cabin", ])

In [46]:
print(df.columns)

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [47]:
X = X.drop("PassengerId", axis=1)

In [48]:
le = LabelEncoder()
X["Sex"] = le.fit_transform(X["Sex"])
X["Embarked"] = le.fit_transform(
    X["Embarked"]
)

In [49]:
X.dtypes

Pclass        int64
Sex           int64
Age         float64
SibSp         int64
Parch         int64
Fare        float64
Embarked      int64
dtype: object

In [50]:
#df.isnull().sum()
X["Age"] = X["Age"].fillna(X["Age"].median())

In [51]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [52]:
model = DecisionTreeClassifier(random_state = 42)
model.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [53]:
pred = model.predict(X_test)
#pred[:10]
#y_test[:10]

In [56]:
accuracy = accuracy_score(y_test, pred)
accuracy
#cm = confusion_matrix(y_test, pred)
#cm

0.7821229050279329

In [55]:
importance = pd.DataFrame({
    "Feature": X.columns ,
  "Importance": model.feature_importances_
})
importance

    Feature  Importance
0    Pclass    0.111619
1       Sex    0.310280
2       Age    0.217041
3     SibSp    0.056342
4     Parch    0.037738
5      Fare    0.242798
6  Embarked    0.024181